#include <nvEncodeAPI.h>

#define MARK_FIX(req_name) const unsigned int FIXBIND_##req_name = req_name;

MARK_FIX(NV_ENCODE_API_FUNCTION_LIST_VER);
MARK_FIX(NV_ENC_CAPS_PARAM_VER);
MARK_FIX(NV_ENC_ENCODE_OUT_PARAMS_VER);
MARK_FIX(NV_ENC_CREATE_INPUT_BUFFER_VER);
MARK_FIX(NV_ENC_CREATE_BITSTREAM_BUFFER_VER);
MARK_FIX(NV_ENC_CREATE_MV_BUFFER_VER);
MARK_FIX(NV_ENC_RC_PARAMS_VER);
MARK_FIX(NV_ENC_CONFIG_VER);
MARK_FIX(NV_ENC_INITIALIZE_PARAMS_VER);
MARK_FIX(NV_ENC_RECONFIGURE_PARAMS_VER);
MARK_FIX(NV_ENC_PRESET_CONFIG_VER);
MARK_FIX(NV_ENC_PIC_PARAMS_MVC_VER);
MARK_FIX(NV_ENC_PIC_PARAMS_VER);
MARK_FIX(NV_ENC_MEONLY_PARAMS_VER);
MARK_FIX(NV_ENC_LOCK_BITSTREAM_VER);
MARK_FIX(NV_ENC_LOCK_INPUT_BUFFER_VER);
MARK_FIX(NV_ENC_MAP_INPUT_RESOURCE_VER);
MARK_FIX(NV_ENC_REGISTER_RESOURCE_VER);
MARK_FIX(NV_ENC_STAT_VER);
MARK_FIX(NV_ENC_SEQUENCE_PARAM_PAYLOAD_VER);
MARK_FIX(NV_ENC_EVENT_PARAMS_VER);
MARK_FIX(NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER);
